version: "3.8"

services:
  nats:
    image: nats:2.7.2
    ports:
      - 8222:8222
      - 4222:4222
      - 6222:6222
    command: [ "-js", "-sd", "data_storage" ]

  back:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nats
    ports:
      - "8000:8000"

  model:
    build:
      context: ../../model_checker/model_checker
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "8001:8001"



